[tool.poetry]
name = "geolib_plus"
version = "0.1.1"
description = "GEOLib+ components"
authors = ["Maarten Pronk <git@evetion.nl>", "Deltares"]
license = "LGPL-3.0-or-later"

[tool.poetry.dependencies]
python = "^3.7"
pydantic = "^1.6"
pyproj = "^2.6"
pandas = "^1.1"
tqdm = "^4.50"
scipy = "^1.5"
lxml = "^4.5"
numpy = "^1.19"
matplotlib = "^3.3"
Shapely = "^1.7"
pyshp = "^2.1"
more-itertools = "^8.6"
netCDF4 = "^1.5"
requests = "^2.26"
geolib = "^1.0"

[tool.poetry.dev-dependencies]
teamcity-messages = "^1.28"
pytest = "^6.1"
coverage = "^5"
pytest-cov = "^2.10"
Sphinx = "^3.2"
releases = "^1.6"
rst2pdf = "^0.98"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

[tool.pytest.ini_options]
testpaths = [
    "tests",
]
markers = [
    "unittest",
    "integrationtest",
    "systemtest",
    "acceptancetest",
    "workinprogress"
]
