[tool.poetry]
name = "geolib_plus"
version = "0.1.1"
description = "GEOLib+ components"
authors = ["Maarten Pronk <git@evetion.nl>", "Deltares"]
license = "LGPL-3.0-or-later"

[tool.poetry.dependencies]
python = "^3.7"
pydantic = "^1.6.1"
pyproj = "^2.6.1"
pandas = "^1.1.3"
tqdm = "^4.50.2"
scipy = "^1.5.2"
lxml = "^4.5.2"
numpy = "^1.19.2"
matplotlib = "^3.3.2"
Shapely = "^1.7.1"
pyshp = "^2.1.2"
more-itertools = "^8.6.0"
netCDF4 = "^1.5.4"

[tool.poetry.dev-dependencies]
teamcity-messages = "^1.28"
pytest = "^6.1.0"
coverage = "^5.3"
pytest-cov = "^2.10.1"
Sphinx = "^3.2.1"
releases = "^1.6.3"
rst2pdf = "^0.98"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

[tool.pytest.ini_options]
testpaths = [
    "tests",
]
markers = [
    "unittest",
    "integrationtest",
    "systemtest",
    "acceptancetest"
]
