[tool.poetry]
name = "geolib_plus"
version = "0.1.0"
description = "GEOLib+ components"
authors = ["Maarten Pronk <git@evetion.nl>", "Deltares"]
license = "LGPL-3.0-or-later"

[tool.poetry.dependencies]
python = "^3.7"
pydantic = "^1.6.1"

[tool.poetry.dev-dependencies]
teamcity-messages = "^1.28"
pytest = "^6.1.0"
coverage = "^5.3"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
