

table1 = {"Veen": {
    "mineraalarm": {"saturated_weight":{"mean":10.5,
                                        "limits":[10,11]},
                    "unsaturated_weight": {"mean":10.5,
                                        "limits":[10,11]}},
    "verslagen": {"saturated_weight":{"mean":10.5,
                                        "limits":[10,11]},
                    "unsaturated_weight": {"mean":10.5,
                                        "limits":[10,11]}},
    "detritus": {"saturated_weight":{"mean":10.5,
                                        "limits":[10,11]},
                    "unsaturated_weight": {"mean":10.5,
                                        "limits":[10,11]}},
    "kleiig": {"saturated_weight":{"mean":11.5,
                                        "limits":[11,12]},
                    "unsaturated_weight": {"mean":11.5,
                                        "limits":[11,12]}},
    "compact": {"saturated_weight":{"mean":11,
                                        "limits":[10,12]},
                    "unsaturated_weight": {"mean":11,
                                        "limits":[10,12]}},
    "Hollandveen": {"saturated_weight":{"mean":10.5,
                                        "limits":[10,11]},
                    "unsaturated_weight": {"mean":10.5,
                                        "limits":[10,11]}},
    "Basisveen": {"saturated_weight":{"mean":11,
                                        "limits":[10,12]},
                    "unsaturated_weight": {"mean":11,
                                        "limits":[10,12]}},
    },
    "Gyttja":{
        "base":{}
    },
    "Klei":{
        "base":{},
        "venig": {"saturated_weight":{"mean":13,
                                        "limits":[12,14]},
                    "unsaturated_weight": {"mean":13,
                                        "limits":[12,14]}},
        "organisch": {"saturated_weight":{"mean":13,
                                        "limits":[12,14]},
                    "unsaturated_weight": {"mean":13,
                                        "limits":[12,14]}},
        "zandig":{"saturated_weight":{"mean":18.5,
                                        "limits":[16,21]},
                    "unsaturated_weight": {"mean":18.5,
                                        "limits":[16,21]}},
        "siltig": {"saturated_weight":{"mean":18.5,
                                        "limits":[16,21]},
                    "unsaturated_weight": {"mean":18.5,
                                        "limits":[16,21]}},
        "Echteld_ondiep":{},
        "Echteld_diep":{},
        "Naaldwijk_ondiep":{},
        "Naalwijk_diep":{},


    },
    "Zand":{
        "base":{"saturated_weight":{"mean":19.5,
                                        "limits":[18,21]},
                    "unsaturated_weight": {"mean":17,
                                        "limits":[16,18]}},
        "matig_gesorteerd":{"saturated_weight":{"mean":19.5,
                                        "limits":[18,21]},
                    "unsaturated_weight": {"mean":17,
                                        "limits":[16,18]}},
        "goed_gesorteerd":{"saturated_weight":{"mean":19.5,
                                        "limits":[18,21]},
                    "unsaturated_weight": {"mean":17,
                                        "limits":[16,18]}},
        "met_kleilaagjes":{"saturated_weight":{"mean":19.5,
                                        "limits":[18,21]},
                    "unsaturated_weight": {"mean":17,
                                        "limits":[16,18]}},
    },
    "Loss":{
        "base":{"saturated_weight":{"mean":18.5,
                                        "limits":[16,21]},
                    "unsaturated_weight": {"mean":18.5,
                                        "limits":[16,21]}}
    },
    "Keileem": {
        "base": {"saturated_weight":{"mean": 21,
                                        "limits": [19, 23]},
                    "unsaturated_weight": {"mean": 21,
                                        "limits": [19,23]}}
    },
    "Dijksmateriaal": {
        "base": {"saturated_weight":{"mean": 17.5,
                                        "limits": [14,21]},
                    "unsaturated_weight": {"mean": 17.5,
                                        "limits":[19,23]}}
    },
}