

table1 = {"Veen": {
    "mineraalarm": {"saturated_weight":{"mean": 10.5,
                                        "limits": [10,11]},
                    "unsaturated_weight": {"mean": 10.5,
                                        "limits":[10, 11]},
                    "shear_strength_ratio":{"mean": 0.42,
                                            "limits": [0.28, 0.54],
                                            "standard_deviation": 0.04,
                                            "low_characteristic_value": 0.28},
                    "POP": {"mean": 11,
                            "limits": [0, 60],
                            "low_characteristic_value": 1}
                    },
    "verslagen": {"saturated_weight":{"mean":10.5,
                                        "limits":[10,11]},
                    "unsaturated_weight": {"mean":10.5,
                                        "limits":[10,11]},
                    "shear_strength_ratio":{"mean": 0.38,
                                            "limits": [0.29, 0.43],
                                            "standard_deviation": 0.03,
                                            "low_characteristic_value": 0.29},
                  "POP": {"mean": 25,
                          "limits": [10, 60],
                          "low_characteristic_value": 15}
                  },
    "detritus": {"saturated_weight":{"mean":10.5,
                                        "limits":[10,11]},
                    "unsaturated_weight": {"mean":10.5,
                                        "limits":[10,11]},
                    "shear_strength_ratio":{"mean": 0.38,
                                            "limits": [0.29, 0.43],
                                            "standard_deviation": 0.03,
                                            "low_characteristic_value": 0.29}},
    "kleiig": {"saturated_weight":{"mean":11.5,
                                        "limits":[11,12]},
                    "unsaturated_weight": {"mean":11.5,
                                        "limits":[11,12]},
                    "shear_strength_ratio":{"mean": 0.29,
                                            "limits": [0.24, 0.38],
                                            "standard_deviation": 0.03,
                                            "low_characteristic_value": 0.24}},
    "compact": {"saturated_weight":{"mean":11,
                                        "limits":[10,12]},
                    "unsaturated_weight": {"mean":11,
                                        "limits":[10,12]},
                    "shear_strength_ratio":{"mean": 0.31,
                                            "limits": [0.30, 0.33],
                                            "standard_deviation": 0.03,
                                            "low_characteristic_value": 0.30}},
    "Hollandveen": {"saturated_weight":{"mean":10.5,
                                        "limits":[10,11]},
                    "unsaturated_weight": {"mean":10.5,
                                        "limits":[10,11]},
                    "shear_strength_ratio":{"mean": 0.42,
                                            "limits": [0.28, 0.54],
                                            "standard_deviation": 0.04,
                                            "low_characteristic_value": 0.28},
                    "POP": {"mean": 11,
                            "limits": [0, 60],
                            "low_characteristic_value": 1}
                    },
    "Basisveen": {"saturated_weight":{"mean":11,
                                        "limits":[10,12]},
                    "unsaturated_weight": {"mean":11,
                                        "limits":[10,12]},
                    "shear_strength_ratio":{"mean": 0.31,
                                            "limits": [0.30, 0.33],
                                            "standard_deviation": 0.03,
                                            "low_characteristic_value": 0.30},
                  "POP": {"mean": 25,
                          "limits": [10, 60],
                          "low_characteristic_value": 15}
                  },
    },
    "Gyttja":{
        "base":{"saturated_weight":{"mean":11.75,
                                        "limits":[10.5,13]},
                    "unsaturated_weight": {"mean":11.75,
                                        "limits":[10.5,13]},
                    "shear_strength_ratio":{"mean": 0.3,
                                            "limits": [0.27, 0.34],
                                            "standard_deviation": 0.03,
                                            "low_characteristic_value": 0.27}}
    },
    "Klei":{
        "base":{"saturated_weight":{"mean":14.5,
                                        "limits":[13,16]},
                    "unsaturated_weight": {"mean":14.5,
                                        "limits":[13,16]},
                    "shear_strength_ratio":{"mean": 0.25,
                                            "limits": [0.22, 0.28],
                                            "standard_deviation": 0.03,
                                            "low_characteristic_value": 0.22},
                "POP": {"mean": 22,
                        "limits": [0, 75],
                        "low_characteristic_value": 10}
                },
        "venig": {"saturated_weight":{"mean":13,
                                        "limits":[12,14]},
                    "unsaturated_weight": {"mean":13,
                                        "limits":[12,14]},
                    "shear_strength_ratio":{"mean": 0.29,
                                            "limits": [0.16, 0.38],
                                            "standard_deviation": 0.06,
                                            "low_characteristic_value": 0.20}},
        "organisch": {"saturated_weight":{"mean":13,
                                        "limits":[12,14]},
                    "unsaturated_weight": {"mean":13,
                                        "limits":[12,14]},
                    "shear_strength_ratio":{"mean": 0.29,
                                            "limits": [0.16, 0.38],
                                            "standard_deviation": 0.06,
                                            "low_characteristic_value": 0.20}},
        "zandig":{"saturated_weight":{"mean":18.5,
                                        "limits":[16,21]},
                    "unsaturated_weight": {"mean":18.5,
                                        "limits":[16,21]},
                    "shear_strength_ratio":{"mean": 0.30,
                                            "limits": [0.20, 0.50],
                                            "standard_deviation": 0.03,
                                            "low_characteristic_value": 0.20}},
        "siltig": {"saturated_weight":{"mean":18.5,
                                        "limits":[16,21]},
                    "unsaturated_weight": {"mean":18.5,
                                        "limits":[16,21]},
                    "shear_strength_ratio":{"mean": 0.30,
                                            "limits": [0.20, 0.50],
                                            "standard_deviation": 0.03,
                                            "low_characteristic_value": 0.20}},
        "Echteld_ondiep": {"POP": {"mean": 27,
                                   "limits": [5, 65],
                                   "low_characteristic_value": 15}},
        "Echteld_diep": {"POP": {"mean": 24,
                                 "limits": [0, 75],
                                 "low_characteristic_value": 8}},
        "Naaldwijk_ondiep": {"POP": {"mean": 25,
                                     "limits": [5, 60],
                                     "low_characteristic_value": 15}},
        "Naalwijk_diep": {"POP": {"mean": 14,
                                  "limits": [0, 30],
                                  "low_characteristic_value": 7}},


    },
    "Zand":{
        "base":{"saturated_weight":{"mean":19.5,
                                        "limits":[18,21]},
                    "unsaturated_weight": {"mean":17,
                                        "limits":[16,18]}},
        "matig_gesorteerd":{"saturated_weight":{"mean":19.5,
                                        "limits":[18,21]},
                    "unsaturated_weight": {"mean":17,
                                        "limits":[16,18]}},
        "goed_gesorteerd":{"saturated_weight":{"mean":19.5,
                                        "limits":[18,21]},
                    "unsaturated_weight": {"mean":17,
                                        "limits":[16,18]}},
        "met_kleilaagjes":{"saturated_weight":{"mean":19.5,
                                        "limits":[18,21]},
                    "unsaturated_weight": {"mean":17,
                                        "limits":[16,18]}},
    },
    "Loss":{
        "base":{"saturated_weight":{"mean":18.5,
                                        "limits":[16,21]},
                    "unsaturated_weight": {"mean":18.5,
                                        "limits":[16,21]},
                    "shear_strength_ratio":{"mean": 0.35,
                                            "limits": [0.20, 0.50],
                                            "standard_deviation": 0.04,
                                            "low_characteristic_value": 0.20}}
    },
    "Keileem": {
        "base": {"saturated_weight":{"mean": 21,
                                        "limits": [19, 23]},
                    "unsaturated_weight": {"mean": 21,
                                        "limits": [19,23]},
                    "shear_strength_ratio":{"limits": [0.1, 1],
                                            "standard_deviation": 0.03,
                                            "low_characteristic_value": 0.10}}
    },
    "Dijksmateriaal": {
        "base": {"saturated_weight":{"mean": 17.5,
                                        "limits": [14,21]},
                    "unsaturated_weight": {"mean": 17.5,
                                        "limits":[19,23]},
                    "shear_strength_ratio":{"mean": 0.31,
                                            "limits": [0.20, 0.50],
                                            "standard_deviation": 0.06,
                                            "low_characteristic_value": 0.20},
                 "POP": {"mean": 30,
                         "limits": [0, 150],
                         "low_characteristic_value": 7}
                 }
    },
}